apiVersion: 1
datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://192.168.40.20:3100
    isDefault: false
    jsonData:
      maxLines: 1000

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://192.168.40.22:9090
    isDefault: true
    jsonData:
      timeInterval: 15s
