groups:
  - name: lab7_alerts
    rules:

      - alert: ServiceDown
        expr: up == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.instance }} is down"
          description: "{{ $labels.job }}/{{ $labels.instance }} has been down for > 30s"

      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[1m]) > 0.1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High 5xx error rate on {{ $labels.instance }}"
          description: "Error rate is {{ $value | humanizePercentage }}"

      - alert: RedisDown
        expr: redis_up == 0
        for: 15s
        labels:
          severity: critical
        annotations:
          summary: "Redis is unreachable"

      - alert: PostgresDown
        expr: pg_up == 0
        for: 15s
        labels:
          severity: critical
        annotations:
          summary: "PostgreSQL is unreachable"

      - alert: HighWorkflowLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{handler="/process-file"}[5m])) > 20
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Gateway /process-file p95 latency > 20s"
          description: "p95={{ $value }}s"
